# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 523877783af0dfc84056741ac28fe6e2e54109a29913618c457582e75df858db55d7a59a4dfca6cc8c7541ad46d6138a403c88232860e6f843d6d2b6786b4a86

test:
  secret_key_base: d25a1afe23dfae7475e6e21e44563b30923747943f9ef80c08de1609c9bccc5467c5e77cf6b5258897695924af4fb7d52fc6b61e1cf7fd829bf766ac3aa1eabf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 6e19c1b88a50bb496d58d949aefee0fad48267339a858cc516e30d168360a3f6efa7c37077499dc1f321bddd67c46092445d227566263f0de10388bb1c83163b

